### PR TITLE
Add winter storage resources to fixtures

### PR DESCRIPTION
**Pull request by igordavydsson**
## Description :sparkles:

Add Helsinki's winter storage resources to fixtures

- [x] Add marked areas and places
- [x] Add unmarked areas

### Related :handshake:

#268 

### Manual testing :construction_worker_man:

Install winter resources by running the following command:
```bash
python manage.py loaddata helsinki-ws-resources.json
```

### CODE REVIEW

**Comment by igordavydsson** [comment]
please, guys, @santtul @a-rmz , test the fixtures locally 🙂

**Comment by a-rmz** [comment]
@igordavydsson raises a duplicate error:
```python
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "resources_winterstorageplacetype_width_length_527e6b8d_uniq"
DETAIL:  Key (width, length)=(3.50, 10.00) already exists.
```

**Comment by a-rmz** [comment]
Cool cool, after cleaning the DB it worked
```
Installed 602 object(s) from 1 fixture(s)
```

**Review by a-rmz — APPROVED** [review]
cool

**Comment by santtul** [comment]
worked for me also! one thing: should we mention running this fixture in the README.md (like we have mentioned the other fixtures)?

**Pull request merged**
