### PR TITLE
Tech | Remove deprecated harbor/winter area map

### PR DESCRIPTION
**Pull request by a-rmz**
## Description :sparkles:
* `HarborMap`/`WinterStorageAreaMap`s are not used (and won't be used). Since we don't support file upload either, let's just get rid of it to avoid extra confusion and unnecessary code

### CODE REVIEW

**Comment by haavikko** [comment]
There are now two HarborMaps in staging db which are obsolete. I didn't notice a migration in this PR to drop the table?

**Comment by haavikko** [comment]
review env deployment seems to fail, it's probably due to the missing migrations to drop the models?

**Review by haavikko — CHANGES_REQUESTED** [review]
Need migrations to drop the tables?

**Comment by a-rmz** [comment]
Whoopsies 😅 quite an important thing to miss... fixed now 👍

**Review by haavikko — APPROVED** [review]
Lookin' good!

**Pull request merged**
